%% Search for a specified operating point for the model - lumped_neck_with_motor_roll.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.12 and Simulink Control Design (TM) 6.1.
%
% Generated on: 03-May-2022 12:24:01

%% Specify the model name
%model = 'lumped_neck_with_motor_roll';

function [op, opreport] = autogen_find_operating_points_roll(model, roll_op_point, opt)
%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - lumped_neck_with_motor_roll/Joints/Config/Solver Configuration/EVAL_KEY/INPUT_1_1_1
% - Default model initial conditions are used to initialize optimization.

% State (2) - lumped_neck_with_motor_roll/Joints/Config/Solver Configuration/EVAL_KEY/INTERNAL_1_1_1
% - Default model initial conditions are used to initialize optimization.

% State (3) - lumped_neck_with_motor_roll/Joints/Config/Solver Configuration/EVAL_KEY/INTERNAL_2_1_1
% - Default model initial conditions are used to initialize optimization.

% State (4) - lumped_neck_with_motor_roll/Joints/roll_revolute
opspec.States(4).x = deg2rad(roll_op_point);
opspec.States(4).Known = true;
opspec.States(4).SteadyState = false;
opspec.States(4).dxMin = 0;
opspec.States(4).dxMax = 0;

% State (5) - lumped_neck_with_motor_roll/Joints/roll_revolute
% - Default model initial conditions are used to initialize optimization.
opspec.States(5).Known = true;
opspec.States(5).SteadyState = false;

% State (6) - lumped_neck_with_motor_roll/Torsional Spring-Damper
% - Default model initial conditions are used to initialize optimization.
opspec.States(6).Known = true;
opspec.States(6).SteadyState = false;
opspec.States(6).dxMin = 0;
opspec.States(6).dxMax = 0;

% State (7) - lumped_neck_with_motor_roll/j1
% - Default model initial conditions are used to initialize optimization.
opspec.States(7).Known = true;
opspec.States(7).SteadyState = false;

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - lumped_neck_with_motor_roll/v
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(1).Known = true;

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - lumped_neck_with_motor_roll/yr
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(1).Known = true;
opspec.Outputs(1).y = roll_op_point;

%% Create the options

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);
end